server:
  port: 8877

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coding_bat
    username: postgres
    password: sarvar3881
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 465
    username: b228d4b55a3249
    password: 59bf8da35e1c58
    properties:
      smtp:
        auth: true
        starttls:
          enable: true

logging:
  config: classpath:log-conf/logback-spring.xml

auth:
  users:
    - email: 'sardor@gmail.com'
      password: 'root123'
      role: 'ADMIN'

application:
  host: "http://localhost:${server.port}"

  file:
    basedir: "files"
    download-url: "${application.host}/api/v1/file/download"

  jwt:
    secret-key: '31321Jwt21cret76575646Key131231wt21cret76575646Key1312311321Jwt21cret76575646Key131231wt21cret76575646Key131231'
    access-token-exp: 86400000 # a day
    refresh-token-exp: 24096000000 # 7 days

  mail:
    from: 'appcodingbat@info.com'
    activate-url: '${application.host}/api/v1/auth/activate/'
